// deklarasi object:
// forrmat:
let namavariabel ={
    properry1: value1,
    property2: value2,
    ....
    propertyN: valueN

};

let player ={
    name: 'Cristiano Ronaldo',
    nationality: 'Portugal'
    current_club: 'Al Nassr'
    club_history; [
        'FC A',
        'REal Madrid',
        'Bahayangkara FC'
    ], <-#16-21 club history:

    market_value: 8900,
    attribute: {
        attacking:{
            shooting: 78,
            finishing: 90,
            dribbling: 90,
        },
        
        
    
    },

}